name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  go-otel-exporter:
    runs-on: ubuntu-18.04

    strategy:
      # if one test fails, do not abort the rest
      fail-fast: false
      matrix:
        include:
          - go-version: 1.13.x
          - go-version: 1.14.x
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...
